### PR TITLE
Cart page #28

### PR DESCRIPTION
**Pull request by TyMazey**
adds destroy action to cart controller and clears the :cart session when hit. test that this clears the cart for a user.

### CODE REVIEW

**Comment by n-flint** [comment]
This looks great Ty, looks ready to merge to me!

**Comment by Vjp888** [comment]
I'll approve for merge, spoke with Noah about the code on this.

**Review by Vjp888 — APPROVED** [review]
I like the added clarity for what each item signifies. 

otherwise tests look really solid.

**Comment by renecasco** [comment]
Looks good to me as well, I'll merge!

**Pull request merged**
