### PR TITLE
Items index page

### PR DESCRIPTION
**Pull request by renecasco**

### CODE REVIEW

**Comment by renecasco** [comment]
Testing for image links to show page is not working, but I verified with save_and_open_page, so the error is in the test syntax and not the functionality

**Comment by renecasco** [comment]
Also, gitignore is not ignoring the coverage folder

**Comment by n-flint** [comment]
Looking good Rene! We might be able to refactor the test a lil (all three are using the same items). But thats no biggie right now. Looks good to merge to me!

**Review by TyMazey — COMMENTED** [review]
Lets just make sure we get all the coverage file out of git in the final itieration and we good

**Comment by TyMazey** [comment]
@n-flint @Vjp888 @renecasco 
had to do a manual merge conflict in Atom for this branch yall wana take a peek and make sure nothing is missing.

**Comment by n-flint** [comment]
Looks like you got everything Ty! I'm up for a merge.

**Pull request merged**
